spring:
  datasource:
    username: root
    password: my-secret-pw
    url: jdbc:mysql://localhost:3306/fornecedor
  jpa:
    hibernate:
      ddl-auto: update
      format-sql: true
    show-sql: true
